// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/recode-sh/cli/internal/aws (interfaces: UserConfigEnvVarsResolver)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	userconfig "github.com/recode-sh/aws-cloud-provider/userconfig"
)

// AWSUserConfigEnvVarsResolver is a mock of UserConfigEnvVarsResolver interface.
type AWSUserConfigEnvVarsResolver struct {
	ctrl     *gomock.Controller
	recorder *AWSUserConfigEnvVarsResolverMockRecorder
}

// AWSUserConfigEnvVarsResolverMockRecorder is the mock recorder for AWSUserConfigEnvVarsResolver.
type AWSUserConfigEnvVarsResolverMockRecorder struct {
	mock *AWSUserConfigEnvVarsResolver
}

// NewAWSUserConfigEnvVarsResolver creates a new mock instance.
func NewAWSUserConfigEnvVarsResolver(ctrl *gomock.Controller) *AWSUserConfigEnvVarsResolver {
	mock := &AWSUserConfigEnvVarsResolver{ctrl: ctrl}
	mock.recorder = &AWSUserConfigEnvVarsResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *AWSUserConfigEnvVarsResolver) EXPECT() *AWSUserConfigEnvVarsResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *AWSUserConfigEnvVarsResolver) Resolve() (*userconfig.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve")
	ret0, _ := ret[0].(*userconfig.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *AWSUserConfigEnvVarsResolverMockRecorder) Resolve() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*AWSUserConfigEnvVarsResolver)(nil).Resolve))
}
